### ISSUE TITLE
关于DDNS域名防火墙规则消失的问题

### ISSUE THREAD

**Issue by icloudu888** [arloor/iptablesUtils#10]
vultr centos7 64位
安装了APPNODE面板
在面板里面安装了IPTABLES防火墙

情况1，
运行一键脚本之后，重启vps，防火墙规则消失

情况2，
运行一键脚本之后，在appnode面板，防火墙原文模式里面，改成编辑模式，什么也不改动，直接保存，重启vps之后，防火墙规则存在。但是，ddns更新之后，规则数量会翻倍。
意思是：转发一个端口，四个规则。会变成八个规则，成对的重复。

刚才支持一下。感谢您的贡献。

**Comment by arloor** [comment]
情况1  使用选项3增加的转发规则会在重启后消失  使用1增加的则不会
情况2 麻烦截下图。。

**Comment by icloudu888** [comment]
情况1
我用的就是选项1 增加到域名的转发，重启之后就这样
![1](https://user-images.githubusercontent.com/37955483/66800666-ac5d7300-ef48-11e9-9fb2-e8677264c2cf.JPG)

情况2
这次居然没有重复规则。。好尴尬。。。。。。。。。。

情况3 新的
添加第一个域名转发，在appnode面板，防火墙原文模式里面，改成编辑模式，什么也不改动，直接保存，重启vps，规则正常的。然后，添加第二个端口转发，脚本操作没有发现异常，但是，面板防火墙里面没有出现规则

**Comment by icloudu888** [comment]
就是，，感觉这个appnode面板的防火墙，，和脚本，有点不是很兼容的意思。。
不好意思。我个人习惯appnode面板了。。
大家都用啥面板啊，不会都是命令行管理吧。。

**Comment by icloudu888** [comment]
啊啊啊，试了好几次，情况2不出现了。。

**Comment by icloudu888** [comment]
情况2确实看不到了。情况1会出现。。情况3，也会出现

**Comment by arloor** [comment]
情况1 是一个bug，晚点会修复。
情况3 添加规则后 需要等待两分钟左右 才会生效

**Comment by icloudu888** [comment]
谢谢回复，么么哒。你要是个妹子，我可以以身相许。

**Comment by arloor** [comment]
> 情况1 是一个bug，晚点会修复。
> 情况3 添加规则后 需要等待两分钟左右 才会生效
情况一的bug已经修复，现在可以执行一次

```
wget -qO natcfg.sh https://raw.githubusercontent.com/arloor/iptablesUtils/master/natcfg.sh && bash natcfg.sh
```

来覆盖老版本

**Comment by icloudu888** [comment]
嗯嗯，感谢，楼主好人。

**Comment by icloudu888** [comment]
亲，又是我。测试了几天。有个情况反映一下。。
我添加了4个端口转发
发现，
排在前面的2个端口，转发稳定和流畅。。
排在后面的2个，经常不通。。重启一下，就好了。这个好的状态，也就保持几个，到十几个小时。。
比如说：
1111
1112
1113
1114
这是四个端口。。无论你，添加域名的顺序是怎样的，
1111和1112.。。。这2个端口，一直是丝滑稳定流畅，总之非常好
1113和1114.。。。这2个端口，就总是不通，重启服务器，就好一会儿。。

奥。。说明一下。。nat机器。。

**Comment by arloor** [comment]
那目标端口和域名都是啥，有能力可以自己看dnat服务的日志，没能力就靠猜吧。

别问啦，再问就烦了

**Comment by icloudu888** [comment]
OK，好的亲
