### ISSUE TITLE
需要更正的bug

### ISSUE THREAD

**Issue by JusufUs** [arloor/iptablesUtils#15]
删除转发后会莫名多出SNAT好几个清理不掉的规则。

**Comment by arloor** [comment]
复现方式有吗
是一定复现还是有可能

**Comment by cckstyn** [comment]
当转发规则达到一定数量后，删除规则时会有可能出现删不完整4条规则的情况。
我个人在10条转发规则左右情况下经常出现这个问题。

**Comment by arloor** [comment]
在考虑使用nftables代替iptables，利用nftables脚本具有事务性（原子性）的特点，可以消除以上bug
但是需要使用高版本系统，例如centos8
