### ISSUE TITLE
规则失效的问题

### ISSUE THREAD

**Issue by lanjuli** [arloor/iptablesUtils#16]
通过DHCP/dhclient获取IP的机器，用这个iptables脚本设置好转发到DDNS的规则，转发生效可用。
当机器再次通过DHCP/dhclient获取了新IP之后，规则全部失效，需要通过此脚本删除已有的DDNS端口转发规则，重新设置新的DDNS端口转发规则，才能重新生效。

centos/debian/ubuntu都会存在此问题。

**Comment by arloor** [comment]
原因：后台有个服务只在一开始的时候读一下本地ip
解决：每次使用dhcp获取新ip后，执行 service dnat restart就行了。不需要删除所有的规则重新加
