### ISSUE TITLE
本机动态探测

### ISSUE THREAD

**Issue by dsmnoi** [arloor/iptablesUtils#17]
希望可以添加本机动态ip探测

如果中转机是动态ip 不会主动探测 需要重启natcfg 才可以重新转发

**Comment by arloor** [comment]
https://github.com/arloor/nftables-nat-rust
解决方案在这





------------------ 原始邮件 ------------------
发件人: dsmn <notifications@github.com>
发送时间: 2020年3月13日 21:16
收件人: arloor/iptablesUtils <iptablesUtils@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: 回复：[arloor/iptablesUtils] 本机动态探测 (#17)





 
希望可以添加本机动态ip探测
 
如果中转机是动态ip 不会主动探测 需要重启natcfg 才可以重新转发

**Comment by dsmnoi** [comment]
这个c7 好像用不了
之前试了一下

**Comment by arloor** [comment]
那就用c8。
我给了解决方案，用不用是你的事情
close and comment
