### ISSUE TITLE
能否增加指定只转发tcp或者udp么？

### ISSUE THREAD

**Issue by ivyshow** [arloor/iptablesUtils#20]
感谢大佬的这个工具，方便了好多
但是就是偶尔只需要转发udp这样就有点不方便
另外能否每个转发增加一个备注选项？
谢谢

**Comment by arloor** [comment]
你可以自己实现
这个工具只能实现90%人的需求
对剩下的10%需求，没时间没精力去搞
所以，一般有人提issue要这要那，我都不会管的



---原始邮件---
发件人: "gogobmx"<notifications@github.com>
发送时间: 2020年4月1日(周三) 晚上11:13
收件人: "arloor/iptablesUtils"<iptablesUtils@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [arloor/iptablesUtils] 能否增加指定只转发tcp或者udp么？ (#20)




 
感谢大佬的这个工具，方便了好多
 但是就是偶尔只需要转发udp这样就有点不方便
 另外能否每个转发增加一个备注选项？
 谢谢

**Comment by ivyshow** [comment]
属于看不懂代码的脚本党，确实自己改不了才跑来问
冒昧能否付费修改呢？可以的话我TG私聊你，不行的话就不打扰你了

**Comment by arloor** [comment]
不好意思，给钱也不做



---原始邮件---
发件人: "gogobmx"<notifications@github.com>
发送时间: 2020年4月1日(周三) 晚上11:51
收件人: "arloor/iptablesUtils"<iptablesUtils@noreply.github.com>;
抄送: "Comment"<comment@noreply.github.com>;"arloor"<admin@arloor.com>;
主题: Re: [arloor/iptablesUtils] 能否增加指定只转发tcp或者udp么？ (#20)




 
属于看不懂代码的脚本党，确实自己改不了才跑来问
 冒昧能否付费修改呢？可以的话我TG私聊你，不行的话就不打扰你了

**Comment by ivyshow** [comment]
嗯，那打扰了，我关issue了
