### ISSUE TITLE
提示tls错误

### ISSUE THREAD

**Issue by Topcckin** [arloor/iptablesUtils#21]
您好，非常感谢您的贡献，让我们用上这个脚本。我在尝试中转V2的时候，普通tcp协议没有问题，正常使用；当准备使用脚本中转ws tls的时候(不中转正常使用)，就中转失败了，客户端提示tls错误。不知道哪里出现问题了，前来问问大佬，谢谢！

**Comment by arloor** [comment]
证书错误，要么设置客户端不验证ssl证书
要么把域名-中转机ip-证书的对应关系搞对


推荐不验证ssl证书



---原始邮件---
发件人: "Topcckin"<notifications@github.com>
发送时间: 2020年4月17日(周五) 凌晨3:22
收件人: "arloor/iptablesUtils"<iptablesUtils@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [arloor/iptablesUtils] 提示tls错误 (#21)




 
您好，非常感谢您的贡献，让我们用上这个脚本。我在尝试中转V2的时候，普通tcp协议没有问题，正常使用；当准备使用脚本中转ws tls的时候，就中转失败了，客户端提示tls错误。不知道哪里出现问题了，前来问问大佬，谢谢！

**Comment by Topcckin** [comment]
谢谢大佬解答。
