### ISSUE TITLE
添加域名转发的时候出现，脚本不存在，请通过github提交issue通知作者

### ISSUE THREAD

**Issue by qqppwskj** [arloor/iptablesUtils#23]
![123](https://user-images.githubusercontent.com/31661873/86564233-72ca0d80-bf98-11ea-9188-49683997f8c9.png)
添加域名转发的时候出现，脚本不存在，请通过github提交issue通知作者
不知道是不是域名的前缀全是数字影响的，之前

字母+数字的正常的

**Comment by arloor** [comment]
不好意思😂
刚刚站挂了，导致出这个错，稍等会就好了



---原始邮件---
发件人: "qqppwskj"<notifications@github.com&gt;
发送时间: 2020年7月6日(周一) 下午2:53
收件人: "arloor/iptablesUtils"<iptablesUtils@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [arloor/iptablesUtils] 添加域名转发的时候出现，脚本不存在，请通过github提交issue通知作者 (#23)




 

 添加域名转发的时候出现，脚本不存在，请通过github提交issue通知作者
 不知道是不是域名的前缀全是数字影响的，之前
 
字母+数字的正常的
