### ISSUE TITLE
在DOCKer 母鸡环境下使用导致Docker 断网

### ISSUE THREAD

**Issue by zhy-one** [arloor/iptablesUtils#26]
网络环境
公网IP4个，IPV6 2 个  Docker 相关网卡3个
使用该脚本添加任意转发后，导致docker 内断网

**Comment by Rakau** [comment]
DK不是很了解

**Comment by qq280579056** [comment]
我也遇到了  老哥

> 网络环境 公网IP4个，IPV6 2 个 Docker 相关网卡3个 使用该脚本添加任意转发后，导致docker 内断网
我也遇到了 老哥有解决方案吗

**Comment by qq280579056** [comment]
> 

iptables -A INPUT -i lo -j ACCEPT

**Comment by qq280579056** [comment]
> 网络环境 公网IP4个，IPV6 2 个 Docker 相关网卡3个 使用该脚本添加任意转发后，导致docker 内断网

iptables -A INPUT -i lo -j ACCEPT

**Comment by tom-proxy** [comment]
确实，安装了docker,再安装此项目，此项目不生效

**Comment by arloor** [comment]
docker 容器网络默认是用的nat，跟本项目是冲突的
