### ISSUE TITLE
有安全隐患

### ISSUE THREAD

**Issue by tristesky** [arloor/iptablesUtils#34]
不检查传入的域名就转发，别人知道了也能白嫖了。
https://aoyouer.com/posts/danger-of-cloudflare-transit/

**Comment by arloor** [comment]
我以为说iptables有安全隐患。原来是中转cloudflare的安全隐患。中转cloudflare这不是主动成为cloudflare的cdn节点吗？

另外，即使是小白，也需要对自己在做什么有基本认知吧。“不检查传入的域名”是谁的问题
