### ISSUE TITLE
dnat-install.sh只更新第一个设置的转发

### ISSUE THREAD

**Issue by anxiaogu** [arloor/iptablesUtils#4]
![6 210350](https://user-images.githubusercontent.com/32951358/64430252-7677d400-d0ea-11e9-9c56-6cd185ebb515.png)

**Comment by arloor** [comment]
确实是这样的，跟里面的机制有关系。

这个脚本实际上创建了一个systemd的服务，systemd服务的实际上做的是：

```
bash /usr/local/bin/dnat.sh 80(本地端口) 80(远程端口) ddns &
```

多次调用dnat-install也只会存在一个实例，也就是只能更新一个ddns。因为没有service dnat restart,所以，只有第一个有效。

这个问题，我有空补充下怎么弄。

**Comment by arloor** [comment]
刚刚更新了下脚本，现在可以重新执行：

```
wget -O dnat-install.sh https://raw.githubusercontent.com/arloor/iptablesUtils/master/dnat-install.sh
bash dnat-install.sh
```
可以多次执行来添加不同端口的ddns转发。
