### ISSUE TITLE
似乎动态转发跑久了会失效?

### ISSUE THREAD

**Issue by Passipur** [arloor/iptablesUtils#7]
root@10-46-122-94:~# journalctl -exu dnat8443
-- No entries --
root@10-46-122-94:~# systemctl status dnat8443
● dnat8443.service - 动态设置iptables转发规则
   Loaded: loaded (/lib/systemd/system/dnat8443.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-09-12 16:50:20 CST; 3 days ago
 Main PID: 17867 (bash)
    Tasks: 2
   Memory: 2.6M
      CPU: 27.667s
   CGroup: /system.slice/dnat8443.service
           ├─16465 sleep 120
           └─17867 /bin/bash /usr/local/bin/dnat.sh 8443 8443 DDNS地址

Warning: Journal has been rotated since unit was started. Log output is incomplete or unavailable.
相关log如上
systemctl restart dnat8443 后可恢复正常并且有正确的log出现
该问题目前仅在UCloud北京Ubuntu 18.04.2 LTS的两台机器上出现
其余机器暂没有发现这个现象

**Comment by Passipur** [comment]
找到问题了
在设置多个转发服务后
两个端口指向一个域名
这个域名指向的IP变更时
同时更新会导致iptables锁定？
日志显示：
Another app is currently holding the xtables lock. Perhaps you want to use the -w option?

**Comment by arloor** [comment]
谢谢反馈，这么说来确实会有问题，且当前这个实现有点难解决

**Comment by arloor** [comment]
出新版本啦，应该能完美解决这个问题。大佬试一下吧。
1. rm -f /lib/systemd/system/dnat*      用于清除老版本的东西
2. 最好reboot下
3. wget -qO natcfg.sh https://raw.githubusercontent.com/arloor/iptablesUtils/master/natcfg.sh && bash natcfg.sh
