### ISSUE TITLE
关于多网卡问题

### ISSUE THREAD

**Issue by xiejiangtian** [arloor/iptablesUtils#8]
想问下大佬，如果NAT是有3个网卡，对应联通电信移动三个出口，如何指定转发流量走特定的出口呢

**Comment by Passipur** [comment]
前段时间刚好有个和你一样的需求
我用的是iptable的SNAT和静态路由实现的
这个应该不是本脚本的适用范围了

**Comment by xiejiangtian** [comment]
> 前段时间刚好有个和你一样的需求
> 我用的是iptable的SNAT和静态路由实现的
> 这个应该不是本脚本的适用范围了

好的！明白 我再研究一下！
