### ISSUE TITLE
关于iptables脚本，只需要udp转发

### ISSUE THREAD

**Issue by neighbor007** [arloor/iptablesUtils#9]
你好，我使用你的natcfg脚本，做ddns域名端口转发，但是我只需要udp转发，我把脚本里的tcp添加规则注释了，但是还是会添加tcp转发，请问还需要改那里，才能只做udp端口转发。

**Comment by Passipur** [comment]
实际上更新是dnat.sh在发挥作用吧
你可能需要fork一份改natcfg中dnat.sh的网址和dnat.sh对应的tcp添加规则

**Comment by arloor** [comment]
楼上大佬说的对的，需要改dnat.sh

**Comment by neighbor007** [comment]
多谢，知道了
